name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch: 
jobs: 
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obter o codigo do Projeto
        uses: actions/checkout@v4.2.2
      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Contrução imagem Docker
        run: echo "Executanto o comando Docker Build"
      - name: Envio da imagem Docker
        run: echo "Executanto o comando Docker Push"        

  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Autenticar na AWS
        run: echo "Executanto o comando aws configure"
      - name: Configurar kubectl
        run: echo "Executanto o comando aws eks update-kubeconfig"
      - name: Deploy dos manifestos no kubernetes
        run: echo "Executanto o comando kubectl apply"        
